rec {
  # Tag check helper
  hasTag = tag: node: node ? tag && node.tag == tag;
  mkNode = tag: attrs: attrs // {inherit tag;};

  mkAbs         = params: body: mkNode "Abs" {inherit params body;};
  mkApp         = func: arg: mkNode "App" {inherit func arg;};
  mkAssert      = cond: body: mkNode "Assert" {inherit cond body;};
  mkBinary      = op: left: right: mkNode "Binary" {inherit op left right;};
  mkConstant    = atom: mkNode "Constant" {inherit atom;};
  mkEnvPath     = path: mkNode "EnvPath" {inherit path;};
  mkHasAttr     = expr: attrPath: mkNode "HasAttr" {inherit expr attrPath;};
  mkIf          = cond: then_: else_: mkNode "If" {inherit cond then_ else_;};
  mkInherit     = scope: names: mkNode "Inherit" {inherit scope names;};
  mkLet         = bindings: body: mkNode "Let" {inherit bindings body;};
  mkList        = items: mkNode "List" {inherit items;};
  mkLiteralPath = path: mkNode "LiteralPath" {inherit path;};
  mkNamedVar    = attrPath: value: mkNode "NamedVar" {inherit attrPath value;};
  mkParam       = paramName: mkNode "Param" {inherit paramName;};
  mkParamSet    = paramSetName: paramList: variadic: mkNode "ParamSet" {inherit paramSetName paramList variadic;};
  mkSelect      = defaultValue: expr: selectPath: mkNode "Select" {inherit defaultValue expr selectPath;};
  mkSet         = rec_: bindings: mkNode "Set" { "rec" = rec_; inherit bindings; };
  mkStr         = str: mkNode "Str" {inherit str;};
  mkSym         = name: mkNode "Sym" {inherit name;};
  mkSynHole     = name: mkNode "SynHole" {inherit name;};
  mkUnary       = op: arg: mkNode "Unary" {inherit op arg;};
  mkWith        = namespace: body: mkNode "With" {inherit namespace body;};

  isAbs         = hasTag "Abs";
  isApp         = hasTag "App";
  isAssert      = hasTag "Assert";
  isBinary      = hasTag "Binary";
  isConstant    = hasTag "Constant";
  isEnvPath     = hasTag "EnvPath";
  isHasAttr     = hasTag "HasAttr";
  isIf          = hasTag "If";
  isLet         = hasTag "Let";
  isList        = hasTag "List";
  isLiteralPath = hasTag "LiteralPath";
  isNamedVar    = hasTag "NamedVar";
  isSelect      = hasTag "Select";
  isSet         = hasTag "Set";
  isStr         = hasTag "Str";
  isSym         = hasTag "Sym";
  isSynHole     = hasTag "SynHole";
  isUnary       = hasTag "Unary";
  isWith        = hasTag "With";

  getAbsBody          = node: node.body;
  getAbsParams        = node: node.params;
  getAppArg           = node: node.arg;
  getAppFunc          = node: node.func;
  getAssertBody       = node: node.body;
  getAssertCond       = node: node.cond;
  getBinaryLeft       = node: node.left;
  getBinaryOp         = node: node.op;
  getBinaryRight      = node: node.right;
  getConstantAtom     = node: node.atom;
  getEnvPathPath      = node: node.path;
  getExprKind         = node: node.tag;
  getHasAttrExpr      = node: node.expr;
  getHasAttrPath      = node: node.attrPath;
  getIfCond           = node: node.cond;
  getIfElse           = node: node.else_;
  getIfThen           = node: node.then_;
  getInheritNames     = node: node.names;
  getInheritScope     = node: node.scope;
  getLetBindings      = node: node.bindings;
  getLetBody          = node: node.body;
  getListItems        = node: node.items;
  getLiteralPathPath  = node: node.path;
  getNamedVarAttrPath = node: node.attrPath;
  getNamedVarValue    = node: node.value;
  getSelectDefault    = node: node.defaultValue;
  getSelectExpr       = node: node.expr;
  getSelectPath       = node: node.selectPath;
  getSetBindings      = node: node.bindings;
  getSetRec           = node: node."rec";
  getStrStr           = node: node.str;
  getSymName          = node: node.name;
  getSynHoleName      = node: node.name;
  getUnaryArg         = node: node.arg;
  getUnaryOp          = node: node.op;
  getWithBody         = node: node.body;
  getWithNamespace    = node: node.namespace;
}
