rec {
  # Tag check helper
  hasTag = tag: node: node ? tag && node.tag == tag;
  mkNode = tag: attrs: attrs // {inherit tag;};

  mkAbs            = params: body: mkNode "Abs" {inherit params body;};
  mkApp            = func: arg: mkNode "App" {inherit func arg;};
  mkAssert         = cond: body: mkNode "Assert" {inherit cond body;};
  mkBinary         = op: left: right: mkNode "Binary" {inherit op left right;};
  mkConstant       = atom: mkNode "Constant" {contents = atom;};
  mkDynamicKey     = antiquoted: mkNode "DynamicKey" {contents = antiquoted;};
  mkEnvPath        = path: mkNode "EnvPath" {contents = path;};
  mkEscapedNewline = mkNode "EscapedNewline" {};
  mkHasAttr        = expr: attrPath: mkNode "HasAttr" {inherit expr attrPath;};
  mkIf             = cond: thenExpr: elseExpr: mkNode "If" {inherit cond thenExpr elseExpr;};
  mkInherit        = scope: names: mkNode "Inherit" {inherit scope names;};
  mkLet            = bindings: body: mkNode "Let" {inherit bindings body;};
  mkList           = items: mkNode "List" {contents = items;};
  mkLiteralPath    = path: mkNode "LiteralPath" {contents = path;};
  mkNamedVar       = attrPath: value: mkNode "NamedVar" {inherit attrPath value;};
  mkParam          = paramName: mkNode "Param" {contents = paramName;};
  mkParamSet       = paramSetName: params: variadic: mkNode "ParamSet" {inherit paramSetName params variadic;};
  mkPlain          = content: mkStr [{ tag = "Plain"; contents = content; }];
  mkSelect         = defaultValue: expr: selectPath: mkNode "Select" {inherit defaultValue expr selectPath;};
  mkSet            = recursive: bindings: mkNode "Set" { inherit recursive bindings; };
  mkStaticKey      = keyName: mkNode "StaticKey" {contents = keyName;};
  mkStr            = value: mkNode "Str" { contents = value; };
  mkSym            = name: mkNode "Sym" {contents = name;};
  mkSynHole        = name: mkNode "SynHole" {contents = name;};
  mkUnary          = op: arg: mkNode "Unary" {inherit op arg;};
  mkWith           = namespace: body: mkNode "With" {inherit namespace body;};

  isAbs            = hasTag "Abs";
  isAntiquoted     = hasTag "Antiquoted";
  isApp            = hasTag "App";
  isAssert         = hasTag "Assert";
  isBinary         = hasTag "Binary";
  isConstant       = hasTag "Constant";
  isDynamicKey     = hasTag "DynamicKey";
  isEnvPath        = hasTag "EnvPath";
  isEscapedNewline = hasTag "EscapedNewline";
  isHasAttr        = hasTag "HasAttr";
  isIf             = hasTag "If";
  isInherit        = hasTag "Inherit";
  isLet            = hasTag "Let";
  isList           = hasTag "List";
  isLiteralPath    = hasTag "LiteralPath";
  isNamedVar       = hasTag "NamedVar";
  isParam          = hasTag "Param";
  isParamSet       = hasTag "ParamSet";
  isPlain          = hasTag "Plain";
  isSelect         = hasTag "Select";
  isSet            = hasTag "Set";
  isStaticKey      = hasTag "StaticKey";
  isStr            = hasTag "Str";
  isSym            = hasTag "Sym";
  isSynHole        = hasTag "SynHole";
  isUnary          = hasTag "Unary";
  isWith           = hasTag "With";

  getAbsBody              = node: node.body;
  getAbsParams            = node: node.params;
  getAppArg               = node: node.arg;
  getAppFunc              = node: node.func;
  getAssertBody           = node: node.body;
  getAssertCond           = node: node.cond;
  getBinaryLeft           = node: node.left;
  getBinaryOp             = node: node.op;
  getBinaryRight          = node: node.right;
  getConstantAtom         = node: node.contents;
  getDynamicKeyAntiquoted = node: node.contents;
  getEnvPathPath          = node: node.contents;
  getExprKind             = node: node.tag;
  getHasAttrExpr          = node: node.expr;
  getHasAttrPath          = node: node.attrPath;
  getIfCond               = node: node.cond;
  getIfElse               = node: node.elseExpr;
  getIfThen               = node: node.thenExpr;
  getInheritNames         = node: node.names;
  getInheritScope         = node: node.scope;
  getLetBindings          = node: node.bindings;
  getLetBody              = node: node.body;
  getListItems            = node: node.contents;
  getLiteralPathPath      = node: node.contents;
  getNamedVarAttrPath     = node: node.attrPath;
  getNamedVarValue        = node: node.value;
  getParamName            = node: node.contents;
  getParamSetName         = node: node.paramSetName;
  getParamSetParams       = node: node.params;
  getParamSetVariadic     = node: node.variadic;
  getSelectDefaultValue   = node: node.defaultValue;
  getSelectExpr           = node: node.expr;
  getSelectPath           = node: node.selectPath;
  getSetBindings          = node: node.bindings;
  getSetRecursive         = node: node.recursive;
  getStaticKeyName        = node: node.contents;
  getStrValue             = node: node.contents;
  getSymName              = node: node.contents;
  getSynHoleName          = node: node.contents;
  getUnaryArg             = node: node.arg;
  getUnaryOp              = node: node.op;
  getWithBody             = node: node.body;
  getWithNamespace        = node: node.namespace;
}
