name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - LICENSE
      - docs/**
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run cabal tests
        run: nix develop --print-build-logs -c cabal test

      - name: Run flake check
        run: nix flake check --print-build-logs
